model_training:
  heart_disease:
    model_type: "LogisticRegression"
    params:
      C: 1.0
      max_iter: 100
  parkinsons:
    model_type: "SVC"
    params:
      C: 1.0
      kernel: "linear"
  diabetes:
    model_type: "SVC"
    params:
      C: 1.0
      kernel: "linear"

evaluation:
  metrics:
    accuracy: true
    precision: true
    recall: true
    f1_score: true
    save_format: "csv"