artifacts_root: artifacts

data_ingestion:
  heart_disease:
    root_dir: data_ingestion/heart_disease
    source_URL: https://github.com/yousefmekhlafi/Multiple-Disease-Prediction/raw/main/heart_data.zip
    local_data_file: data_ingestion/heart_disease_data.zip
    unzip_dir: data_ingestion/heart_disease
  parkinsons:
    root_dir: data_ingestion/parkinsons
    source_URL: https://github.com/yousefmekhlafi/Multiple-Disease-Prediction/raw/main/parkinsons_data.zip
    local_data_file: data_ingestion/parkinsons_data.zip
    unzip_dir: data_ingestion/parkinsons
  diabetes:
    root_dir: data_ingestion/diabetes
    source_URL: https://github.com/yousefmekhlafi/Multiple-Disease-Prediction/raw/main/diabetes_data.zip
    local_data_file: data_ingestion/diabetes_data.zip
    unzip_dir: data_ingestion/diabetes

data_validation:
  heart_disease:
    train_data_file: data_ingestion/heart_disease/heart_train_data.csv
    valid_data_file: data_ingestion/heart_disease/heart_valid_data.csv
    test_data_file: data_ingestion/heart_disease/heart_test_data.csv
  parkinsons:
    train_data_file: data_ingestion/parkinsons/parkinsons_train_data.csv
    valid_data_file: data_ingestion/parkinsons/parkinsons_valid_data.csv
    test_data_file: data_ingestion/parkinsons/parkinsons_test_data.csv
  diabetes:
    train_data_file: data_ingestion/diabetes/diab_train_data.csv
    valid_data_file: data_ingestion/diabetes/diab_valid_data.csv
    test_data_file: data_ingestion/diabetes/diab_test_data.csv

model_training:
  heart_disease:
    model_type: LogisticRegression
    params:
      C: 1.0
      solver: lbfgs
    scaler: StandardScaler
  parkinsons:
    model_type: SVC
    params:
      kernel: linear
      C: 1.0
    scaler: StandardScaler
  diabetes:
    model_type: SVC
    params:
      kernel: linear
      C: 1.0
    scaler: StandardScaler

model_evaluation:
  findings_file: artifacts/evaluation/findings.txt
  models:
    heart_disease:
      model_path: artifacts/models/heart_disease_model.pkl
    parkinsons:
      model_path: artifacts/models/parkinsons_model.pkl
    diabetes:
      model_path: artifacts/models/diabetes_model.pkl
  data_paths:
    heart_disease: artifacts/data/heart_disease_test_data.csv
    parkinsons: artifacts/data/parkinsons_test_data.csv
    diabetes: artifacts/data/diabetes_test_data.csv
